#Simple Start Docker Compose File
#Download file or copy contents onto your host machine in a docker-compose.yml file
#run 'docker-compose up -d'
version: '3.3'
services:
  fasten:
    image: ghcr.io/fastenhealth/fasten-onprem:main
    container_name: fasten
    restart: unless-stopped 
#Go to http://localhost:9090 and create an account to get started 
    ports:
      - '9090:8080'
#Persistent storage. DB will be saved in the volume and not lost when you stop the container      
    volumes:
       - './fasten:/opt/fasten/db/'

